name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker-amd:
    runs-on: ubuntu-latest
    environment: docker 

    steps:
      - name: Move Docker storage to /mnt
        run: |
          sudo systemctl stop docker
          sudo rm -rf /var/lib/docker
          sudo mkdir /mnt/docker
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker

      # - name: Delete huge unnecessary tools folder
      #   run: |
      #     df -h
      #     rm -rf /opt/hostedtoolcache
      #     sudo swapoff -a
      #     sudo rm -f /swapfile
      #     sudo apt-get autoremove -y
      #     sudo apt clean
      #     df -h
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/multimeditron-git:latest-amd64

  docker-arm:
    runs-on: ubuntu-24.04-arm
    environment: docker 

    steps:
      - name: Show available space
        run: |
          df -h
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/multimeditron-git:latest-arm64

